paginate_per_page: 18
default_per_page: 10
seed_time: 100
window: 2
param_name: "q[page]"
book:
  num_page_min: 1
  num_page_max: 10000
activities:
  followed: followed
  unfollowed: unfollowed
  reviewed: reviewed
  commented: commented
  read: read
  favorited: favorited
validates:
  comment:
    minlength: 10
  review:
    minlength: 10
category:
  per_page: 10
relationships: ["following", "followers"]
